### ISSUE TITLE
Document running InfluxDB as a Windows service

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs-v2#2711] opened 2021-06-15 19:58 UTC
Need a set of instructions for InfluxDB on Windows for setting it up and running it as a service....

Telegraf  example: https://docs.influxdata.com/telegraf/v1.18/administration/windows_service/

**Comment by pierwill** [comment] 2021-07-27 17:01
Checking with the team, but it looks like this is not currently supported for InfluxDB 2.x.

**Comment by pierwill** [comment] 2022-03-29 18:10
Closing as possible duplicate of #1060.

**Closed by pierwill** 2022-03-29 18:10 UTC
Labels: hold off, InfluxDB v2, Proposal
