### ISSUE TITLE
Document the `/debug/pprof` endpoint

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#3413] opened 2021-11-17 19:21 UTC
We need to document the `/debug/pprof` API endpoint which provides InfluxDB profiling data. This can be really helpful when troubleshooting.

Users can disable pprof by starting `influxd` with the `pprof-disabled` option set to true:

```sh
influxd --pprof-disabled
```

**Comment by jstirnaman** [comment] 2022-02-17 16:37
Duplicate of #3414

**Closed** 2022-04-27 18:49 UTC
Labels: duplicate, InfluxDB v2, api
