### ISSUE TITLE
Python Client Lib --  https:// not present in the URL for the Cloud URLs

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs-v2#2992] opened 2021-08-09 18:49 UTC
This documentation: https://docs.influxdata.com/influxdb/cloud/api-guide/client-libraries/python/ is wrong/misleading.

Specifically, the examples (it's there multiple times) gives:
```
# Store the URL of your InfluxDB instance
url="http://us-west-2-1.aws.cloud2.influxdata.com"
```
Note the http. If I'm a user and just edit the domain without noting the scheme, then my initial request will go out via http.

This fails for multiple reasons. But, the examples should correctly use `https://` throughout.

**Comment by pierwill** [comment] 2021-08-09 20:58
This one is tricky, and has to do with the URL selector. [This page](https://github.com/influxdata/docs-v2/blob/master/content/influxdb/cloud/api-guide/client-libraries/python.md) is a duplicate of the OSS page using `{{< duplicate-oss >}}`. If the `https://localhost:8086` in the OSS page is changed to `https`, the cloud URL shows with `http`, but so does the `localhost` example. Since people are usually not using TLS when getting started with OSS, this could cause its own problems.

The defined URLs for Cloud in [`influxdb_urls.yml`](https://github.com/influxdata/docs-v2/blob/dae00bd5373763eba077f9561884fdbb38e0f4b4/data/influxdb_urls.yml) do use HTTPS, which is good. The issue then is likely with the URL selector.

@sanderson: could you take a look at this?

**Comment by jstirnaman** [comment] 2021-08-09 21:02
@pierwill @timhallinflux Likely caused by changes we made to replace hostname patterns with cloud hostnames in code examples. I'm already working on a related issue so will test this as well.

**Closed** 2021-08-10 14:29 UTC
Labels: bug, InfluxDB Cloud
