### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by appletreeisyellow** [influxdata/docs-v2#4001] opened 2022-05-09 21:52 UTC
I tried to see the telegraf configuration documentation (https://docs.influxdata.com/telegraf/v1.22/administration/configuration/), and I got an 404 page not found. 

<img width="917" alt="Screen Shot 2022-05-09 at 4 49 04 PM" src="https://user-images.githubusercontent.com/14298407/167504558-d469d91d-f071-4cba-b00f-a114bc82bd08.png">

##### Relevant URLs
- https://docs.influxdata.com/telegraf/v1.22/install/
- https://docs.influxdata.com/telegraf/v1.22/administration/configuration/

**Comment by sanderson** [comment] 2022-05-13 21:06
Duplicate of #3983

Closing.

**Closed by sanderson** 2022-05-13 21:06 UTC
Labels: Telegraf, product:telegraf
