### ISSUE TITLE
Telegraf Issue on Ubuntu When Adding the InfluxData repository

### ISSUE THREAD

**Issue by ThePieMonster** [influxdata/docs-v2#1729] opened 2020-10-28 20:55 UTC
## Description

When following the docs to add the repo for telegraf I am getting a malformed entry error when running `apt-get update` afterwards.

Section of the doc in question
![image](https://user-images.githubusercontent.com/11359134/97495238-6564d480-1935-11eb-9566-b525185d27e9.png)

/etc/apt/sources.list.d/influxdb.list
![image](https://user-images.githubusercontent.com/11359134/97495287-701f6980-1935-11eb-8895-9f7f7989aeaf.png)

apt-get update command
![image](https://user-images.githubusercontent.com/11359134/97495316-7ad9fe80-1935-11eb-9eab-b8e31ca9a36c.png)

## Relevant URLs
https://docs.influxdata.com/telegraf/v1.16/introduction/installation/

**Comment by reimda** [comment] 2020-10-29 18:42
Hi @ThePieMonster, I think the cause of this is that /etc/lsb-release doesn't exist on debian/ubuntu any more.  From a quick search online I get the impression that it existed on all nearly all debian/ubuntu systems in the past but that newer versions have removed it.

Could you try out some updated installation instructions? 

First, clear out the broken source from the old instructions:
sudo rm /etc/apt/sources.list.d/influxdb.list

Then try these updated instructions:
wget -qO- https://repos.influxdata.com/influxdb.key | sudo apt-key add -
source /etc/os-release
echo "deb https://repos.influxdata.com/${ID,,} ${VERSION_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list

then continue with the existing instructions:
sudo apt-get update && sudo apt-get install telegraf
sudo systemctl start telegraf

**Comment by ThePieMonster** [comment] 2020-10-30 03:35
@reimda  Thanks that did the trick!

Btw, is there a way to monitor incoming requests/logs in Telegraf? _Using Ubuntu_

**Comment by noramullen1** [comment] 2020-10-30 03:58
Thanks @ThePieMonster and @reimda! I created a PR to update the docs instructions. Dave, can you take a look to confirm?

**Comment by ThePieMonster** [comment] 2020-10-30 04:10
The install is good now, but after a reboot I did want to mention that I am seeing this when running `systemctl status telegraf`.

![image](https://user-images.githubusercontent.com/11359134/97658956-ac3cf200-1a3b-11eb-966f-d8d68ef500a7.png)

Perhaps I made a mistake in the config or something. Anyway to get better error reporting on why the service failed to start?

**Comment by ThePieMonster** [comment] 2020-10-30 18:57
> @ThePieMonster What Ubuntu version are you using? I want to try to reproduce the error you get after rebooting

18.04 Server 
https://releases.ubuntu.com/18.04/

**Comment by reimda** [comment] 2020-11-02 23:14
Hi @ThePieMonster, I installed a vm of ubuntu 18.04 server from ubuntu-18.04.5-live-server-amd64.iso at the page you linked.  I was able to install telegraf by following the instructions at https://docs.influxdata.com/telegraf/v1.16/introduction/installation/ without any trouble.  It looks like the error you had was specific to your installation.

```
root@ubuntu:~# wget -qO- https://repos.influxdata.com/influxdb.key | sudo apt-key add -
OK
root@ubuntu:~# source /etc/lsb-release
root@ubuntu:~# echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
deb https://repos.influxdata.com/ubuntu bionic stable
root@ubuntu:~#
```

It could be that your /etc/lsb-release file has been modified or that maybe you skipped the middle step (source /etc/lsb-release).  This is what my /etc/lsb-release looks like for reference:

```
root@ubuntu:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
root@ubuntu:~#
```
I also rebooted and checked "systemctl status telegraf".  It reports telegraf is running with no problems.

I'm going to close this because there doesn't seem to be a problem with the docs.

**Closed by reimda** 2020-11-02 23:14 UTC
