### ISSUE TITLE
State whether Grafana Cloud works with InfluxDB 2.0

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#834] opened 2020-03-13 00:40 UTC
_Describe the issue here._

##### Relevant URLs

On https://v2.docs.influxdata.com/v2.0/visualize-data/other-tools/grafana/, there's no statement of whether Grafana Cloud works with InfluxDB 2.0 (OSS or Cloud), and if so, how to do the integration.

It explains how to get things working with on-prem Grafana, but that's not the same as Grafana Cloud.

**Comment by sanderson** [comment] 2020-03-13 15:28
Closing. Duplicate of #737. @alsargent Grafana doesn't cover how to enable plugins in their cloud offering documentation and we don't have access to a Grafana Cloud account (that I'm aware of).

**Closed by sanderson** 2020-03-13 15:28 UTC
