### ISSUE TITLE
Explain how to look up a dashboard ID

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#1286] opened 2020-08-10 22:32 UTC
Today there's nothing in our documentation AFAICT that explains how to look up the ID of a dashboard. As a result, we need to write our own descriptions in blog posts, such as this one that's about to be published:

![image](https://user-images.githubusercontent.com/20701/89837635-39983680-db1e-11ea-8599-93925165589e.png)

We direct readers to the doc pages for the InfluxDB Cloud URL and Cloud org ID (thanks for those). But most of the text for this section is explaining how to get a dashboard ID.

##### Relevant URLs
https://v2.docs.influxdata.com/v2.0/visualize-data/dashboards/

... this doc page should probably go somewhere in this section.

##### What products and version are you using?

InfluxDB Cloud 2.

**Comment by noramullen1** [comment] 2020-08-10 23:13
Closing because this is a duplicate of an issue you opened four days ago: https://github.com/influxdata/docs-v2/issues/1278

**Closed by noramullen1** 2020-08-10 23:13 UTC
