### ISSUE TITLE
Documentation site hogs system resources

### ISSUE THREAD

**Issue by rask** [influxdata/docs-v2#1618] opened 2020-10-07 14:48 UTC
The documentation site for some reason hogs resources to the point that my PC with a relatively new i7 CPU and with 8GB RAM freezes to an inoperable state. I am not sure how to debug the issue as I'm not a frontend developer.

I've been working on integrating one of our tools with InfluxDB, but not being able to read the official documentation for longer than 1-2 minutes at a time (either by remembering to close and reopen a browser tab every once in a while, or by encountering a PC/browser crash and rebooting) makes it hard.

##### Relevant URLs

Happens all over the place in the docs, but mostly I've been browsing https://docs.influxdata.com/influxdb/v1.8/ and subsections therein. Especially https://docs.influxdata.com/influxdb/v1.8/administration/config/ seems to provide a crash 90% of the time for me.

##### What products and version are you using?

I browse using latest Ubuntu and latest Firefox. As said I have enough system resources to browse most of the internet, but only LinkedIn has come close to being such a resource hog. I've tried browsing with all browser extensions disabled, and with nearly all irrelevant system services disabled as well to see if there are some clashes between the browser and them.

**Comment by pierwill** [comment] 2020-10-07 16:58
@rask: Strange, we haven't encountered this on our end. Can't think of what might be causing this... We'll take a look. In the meantime, any more information you could provide might be helpful.

**Comment by rask** [comment] 2020-10-07 17:33
Thanks, will try to see if I can gather some more information. DIfficult though as I don't know how the site itself "works" and having just a minute or two to investigate before it exploding does not help. :D

**Comment by kelseiv** [comment] 2021-08-03 04:01
Thank you, @rask @pierwill -- we've made several performance enhancements to our site in the past few months (cc and thank you, @sanderson @tkyocum). 

To be sure, is this an issue you're still experiencing? No pressure to test...just want to check back-in to see if it makes sense to close this issue...or verify we need to dig a bit deeper.

**Comment by jstirnaman** [comment] 2021-12-22 15:52
Closing this since I couldn't reproduce it and we haven't heard any other complaints.
I tested it in:
- Brave (Chrome), Firefox, or Safari on Mac OS
- Brave and Firefox on Windows 10.

**Closed by jstirnaman** 2021-12-22 15:52 UTC
Labels: bug, requires research
