### ISSUE TITLE
Document how to connect Grafana Cloud to InfluxDB

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#1037] opened 2020-05-13 18:16 UTC
On https://v2.docs.influxdata.com/v2.0/visualize-data/other-tools/grafana/, we talk about how to connect InfluxDB to Grafana *local* but not Grafana *Cloud*. See step 4 below; localhost:3000 is Grafana local.

![image](https://user-images.githubusercontent.com/20701/81848848-96c62100-950a-11ea-8b24-249e35935af8.png)

Since Grafana is used by ~80% of our Cloud 2 customers, it's important that we make documentation page as complete as possible.

If Grafana Cloud doesn't yet support our Flux plugin, please state that's the case.

##### Relevant URLs

https://v2.docs.influxdata.com/v2.0/visualize-data/other-tools/grafana/

##### What products and version are you using?

Cloud 2, Grafana Cloud.

**Comment by sanderson** [comment] 2020-05-13 18:19
Duplicate of #737, closing. @alsargent Nobody on the docs team has access to a Grafana Cloud account and there doesn't appear to be information about enabling plugins in Grafana Cloud. Any help or information would be appreciated.

**Closed by sanderson** 2020-05-13 18:19 UTC
