### ISSUE TITLE
Add influx task retry-failed to docs pages

### ISSUE THREAD

**Issue by russorat** [influxdata/docs-v2#2261] opened 2021-03-08 19:46 UTC
https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/task/

This PR adds an option to `retry-failed` tasks for a given run-id. We need to add docs pages for it.

**Comment by sanderson** [comment] 2021-03-08 19:53
Duplicate of #2095

**Closed by sanderson** 2021-03-08 19:53 UTC
