### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by Karrun** [influxdata/docs-v2#4016] opened 2022-05-13 19:26 UTC
_Missing documentation_

##### Relevant URLs
- https://docs.influxdata.com/telegraf/v1.22/administration/configuration/

##### What products and version are you using?
- Telegraf issues at https://github.com/influxdata/telegraf

**Comment by sanderson** [comment] 2022-05-13 21:05
Duplicate of #3983

Closing.

**Closed by sanderson** 2022-05-13 21:05 UTC
