### ISSUE TITLE
Explain how to use Grafana Cloud with InfluxDB

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#1195] opened 2020-07-09 23:11 UTC
In our v2 documentation, we explain how we integrate with Grafana on-prem (localhost:3000) but not how to integrate with Grafana Cloud. We should provide instructions on how to integrate:

- Grafana Cloud w/ InfluxDB Cloud 2
- Grafana on-prem with InfluxDB OSS 2.0
- Grafana on-prem with InfluxDB Cloud 2

(Grafana Cloud can't work with InfluxDB OSS 2.0 behind a firewall.)

##### Relevant URLs
https://v2.docs.influxdata.com/v2.0/visualize-data/other-tools/grafana/

**Comment by sanderson** [comment] 2020-07-10 03:43
Duplicate of #1037, #834, and #737

**Closed by sanderson** 2020-07-10 03:43 UTC
