### ISSUE TITLE
InfluxQL & InfluxDB 2.0

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs-v2#1194] opened 2020-07-09 23:06 UTC
Please describe how to use InfluxQL with InfluxDB 2.0. Currently, this isn't mentioned anywhere in our doc.

##### Relevant URLs
https://v2.docs.influxdata.com/v2.0/

**Comment by sanderson** [comment] 2020-07-10 03:39
Duplicate of #1184

**Closed by sanderson** 2020-07-10 03:39 UTC
