### ISSUE TITLE
Mosaic Tile: new feature map type

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/docs-v2#1975] opened 2020-12-10 21:59 UTC
Mosaic is a new map type in the Cloud v2 UI.  It is currently behind a feature flag and not available to production users.  It is available in Tools, and does require some finishing touches before it's ready to release.

##### Relevant URLs
Epic link:
https://app.zenhub.com/workspaces/applicationmonitoring-5e3b05772922e316b3a210a4/issues/influxdata/giraffe/199

Final story:
https://app.zenhub.com/workspaces/applicationmonitoring-5e3b05772922e316b3a210a4/issues/influxdata/idpe/8336

Defect:
https://app.zenhub.com/workspaces/applicationmonitoring-5e3b05772922e316b3a210a4/issues/influxdata/idpe/8443

##### What products and version are you using?
Cloud v2 UI

**Comment by sanderson** [comment] 2021-03-04 20:22
Duplicate of #1290

**Closed by sanderson** 2021-03-04 20:22 UTC
Labels: InfluxDB Cloud, priority
