### ISSUE TITLE
Get started with InfluxDB Docker

### ISSUE THREAD

**Issue by bauermww** [influxdata/docs-v2#2387] opened 2021-04-06 08:48 UTC
the command igores the --volume paramter

docker run \
    --name influxdb \
    -p 8086:8086 \
    --volume $PWD:/root/.influxdbv2 \
    influxdb:2.0.4

is not working.

If I use 

docker run \
    --name influxdb \
    -p 8086:8086 \
    --volume $PWD:/var/lib/influxdb2 \
    influxdb:2.0.4

it is working

##### Relevant URLs
https://docs.influxdata.com/influxdb/v2.0/get-started/?t=Docker

**Comment by HanschDennis** [comment] 2021-04-15 15:37
I can confirm the issue. Another option is to use "quay.io/influxdb/influxdb:v2.0.4" instead of "influxdb:2.0.4". In this image "/root/.influxdbv2" is configured by default.

**Comment by kelseiv** [comment] 2021-04-26 00:51
Thank you, @bauermww and @HanschDennis, closing as duplicate of https://github.com/influxdata/docs-v2/issues/2385. We will be resolving this issue very soon!

**Closed by kelseiv** 2021-04-26 00:51 UTC
Labels: duplicate
