### ISSUE TITLE
schema measurements example not working

### ISSUE THREAD

**Issue by mberntsen** [influxdata/docs-v2#3849] opened 2022-03-14 09:14 UTC
error @3:1-3:13: undefined identifier measurements
after prepending 'schema.':
error @3:1-3:71: found unexpected argument start

##### Relevant URLs
- https://docs.influxdata.com/flux/v0.x/stdlib/influxdata/influxdb/schema/measurements/
- _Provide other relevant URLs (project issues, community threads, etc.)_

**Comment by sanderson** [comment] 2022-03-14 16:29
Duplicate of https://github.com/influxdata/influxdb/issues/23166

**Closed by sanderson** 2022-03-14 16:29 UTC
